import { Express } from "express";
import userAuthRouter from "./user-auth";
import adminAuthRouter from "./admin-auth";
import adminPdfRoutes from "./admin-pdf-routes";
import adminPdfRoutesV2 from "./admin-pdf-routes-v2";
import adminRoutes from "./admin-routes";
import aiRoutes from "./ai-routes";
import aiSalesSuggestion from "./ai-sales-suggestion";
import authClean from "./auth-clean";
import authUsernameOnboarding from "./auth-username-onboarding";
import bulkActionsRoutes from "./bulk-actions-routes";
import calendarRoutes from "./calendar-routes";
import commentAutomationRoutes from "./comment-automation-routes";
import customEmailRoutes from "./custom-email-routes";
import dashboardRoutes from "./dashboard-routes";
import emailOtpRoutes from "./email-otp-routes";
import emailStatsRoutes from "./email-stats-routes";
import leadIntelligence from "./lead-intelligence";
import oauthRoutes from "./oauth";
import otpRoutes from "./otp-routes";
import outreach from "./outreach";
import paymentApproval from "./payment-approval";
import paymentCheckout from "./payment-checkout";
import salesEngine from "./sales-engine";
import stripePaymentConfirmation from "./stripe-payment-confirmation";
import videoAutomationRoutes from "./video-automation-routes";
import voiceRoutes from "./voice-routes";
import webhookRouter from "./webhook";
import whatsappConnect from "./whatsapp-connect";
import whatsappOtpRoutes from "./whatsapp-otp-routes";
import whatsappRoutes from "./whatsapp-routes";
import workerRoutes from "./worker";

export async function registerRoutes(app: Express) {
  // Mount all routes
  app.use("/api/user/auth", userAuthRouter);
  app.use("/api/admin/auth", adminAuthRouter);
  app.use("/api/admin/pdf", adminPdfRoutes);
  app.use("/api/admin/pdf-v2", adminPdfRoutesV2);
  app.use("/api/admin", adminRoutes);
  app.use("/api/ai", aiRoutes);
  app.use("/api/ai/sales-suggestion", aiSalesSuggestion);
  app.use("/api/auth/clean", authClean);
  app.use("/api/auth/username", authUsernameOnboarding);
  app.use("/api/bulk", bulkActionsRoutes);
  app.use("/api/calendar", calendarRoutes);
  app.use("/api/comments", commentAutomationRoutes);
  app.use("/api/email/custom", customEmailRoutes);
  app.use("/api/dashboard", dashboardRoutes);
  app.use("/api/email/otp", emailOtpRoutes);
  app.use("/api/email/stats", emailStatsRoutes);
  app.use("/api/leads/intelligence", leadIntelligence);
  app.use("/api/oauth", oauthRoutes);
  app.use("/api/otp", otpRoutes);
  app.use("/api/outreach", outreach);
  app.use("/api/payment/approval", paymentApproval);
  app.use("/api/payment/checkout", paymentCheckout);
  app.use("/api/sales", salesEngine);
  app.use("/api/stripe/confirmation", stripePaymentConfirmation);
  app.use("/api/video", videoAutomationRoutes);
  app.use("/api/voice", voiceRoutes);
  app.use("/webhook", webhookRouter);
  app.use("/api/whatsapp/connect", whatsappConnect);
  app.use("/api/whatsapp/otp", whatsappOtpRoutes);
  app.use("/api/whatsapp", whatsappRoutes);
  app.use("/api/worker", workerRoutes);

  return app;
}
