/**
 * Disclaimer Generator
 * Auto-prepends legal disclaimers to AI-generated messages
 * Keeps disclaimers hidden from frontend but logged for compliance
 */

export interface DisclaimerConfig {
  channel: 'email' | 'sms' | 'voice';
  companyName?: string;
}

/**
 * Generate disclaimer for AI messages
 * Blends naturally into message to comply with legal requirements
 */
export function generateDisclaimerPrefix(config: DisclaimerConfig): string {
  const { channel, companyName = 'Audnix' } = config;

  // Different disclaimers for different channels
  // Keep them concise so they blend into the natural message
  const disclaimers: Record<string, string> = {
    email: `[Automated message from ${companyName} - This message was generated by AI to continue our conversation. For official policies and commitments, please refer to our full Terms of Service.]`,



    sms: `[Automated: This message is informational and AI-generated. See our terms for official commitments.]`,

    voice: `This is an automated message from ${companyName}. `, // Voice: subtle prefix to sound natural
  };

  return disclaimers[channel] || disclaimers.email;
}

/**
 * Prepend disclaimer to message (internal - not shown to leads)
 * This is stored in the database for audit trail and legal compliance
 */
export function prependDisclaimerToMessage(
  messageBody: string,
  channel: 'email' | 'sms' | 'voice',
  companyName?: string
): {
  messageWithDisclaimer: string;
  disclaimerPrefix: string;
} {
  const disclaimerPrefix = generateDisclaimerPrefix({ channel, companyName });

  // For email: disclaimer at the end (better UX)
  // For others: prepend naturally
  let messageWithDisclaimer = messageBody;

  if (channel === 'email') {
    messageWithDisclaimer = `${messageBody}\n\n${disclaimerPrefix}`;
  } else if (channel === 'voice') {
    // Voice: prepend naturally so it sounds like part of the message
    messageWithDisclaimer = `${disclaimerPrefix}${messageBody}`;
  } else {
    // SMS: prepend
    messageWithDisclaimer = `${disclaimerPrefix}\n\n${messageBody}`;
  }

  return {
    messageWithDisclaimer,
    disclaimerPrefix,
  };
}

/**
 * Generate audit trail entry for disclaimer
 * Logs that a disclaimer was sent with this message
 */
export function createDisclaimerAuditEntry(messageId: string, channel: string) {
  return {
    actionType: 'disclaimer_included',
    channel,
    messageId,
    timestamp: new Date(),
    details: `Disclaimer prepended to ${channel} message for legal compliance`,
  };
}
